services:
  apivallabus:
    build: .
    container_name: apivallabus
    image: vallabus/apivallabus:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GTFS_REFRESH_RATE=27000
      - GTFS_RT_EXPIRATION_SECONDS=180
