# Simple workflow for deploying static content to GitHub Pages
name: Update GTFS static files
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
  # Time is in UTC timezone, 6:35AM CEST 
  - cron: '35 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npm run getGtfs
        git config user.name github-actions-bot
        git config user.email github-actions-bot@github.com
        git add gtfs-files
        git diff --staged --quiet || (git commit -m "[bot] Update GTFS static files" && git push origin main)
